grpc:
  server:
    port: 0

spring:
  application:
    name: analyzer
  main:
    log-startup-info: false
    banner-mode: off
  kafka:
    properties:
      bootstrap-servers: "localhost:9092"
      key-deserializer-class: "org.apache.kafka.common.serialization.VoidDeserializer"
      consumer:
        enable-auto-commit: false
        poll-timeout-ms: 500
        group-ids:
          analyzer-user-actions-group-id: "analyzer-user-actions-group"
          analyzer-event-similarity-group-id: "analyzer-events-similarity-group"
      topics:
        user-actions-topic: "stats.user-actions.v1"
        event-similarity-topic: "stats.events-similarity.v1"
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:6542/ewm_ratings_db
    driverClassName: org.postgresql.Driver
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org:
      springframework:
        context: ERROR
        jdbc: DEBUG
        cloud.netflix.eureka: INFO
      hibernate:
        SQL: DEBUG
      apache.kafka: ERROR
    root: INFO